
services:
  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
    env_file: .env
    entrypoint: docker/entrypoint.sh
    depends_on:
      mysql:
        condition: service_healthy

  nginx:
    image: ghcr.io/ame180/nginx-php:latest
    environment:
      APP_PATH: /app
    volumes:
      - .:/app
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - php

  mysql:
    image: ghcr.io/ame180/mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql: